version: "3"
services:
  app:
    build:
      target: dataops-image
      context: .
    ports:
      - "127.0.0.1:5066:8000"
    environment:
      port: 8000
      HOST: 0.0.0.0
      RDS_HOST: postgres-db
      RDS_PORT: 5432
      RDS_USERNAME: postgres
      RDS_PASSWORD: postgres
      RDS_NAME: dataops
      RDS_SCHEMA: dataops
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis

  redis:
    image: redis:6.0.8
    command: redis-server --requirepass redis
    ports:
      - "7379:6379"

  postgres-db:
    image: 'postgres:12-alpine'
    ports:
      - 5500:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql
      - ./migrations/scripts/create_db.sql:/docker-entrypoint-initdb.d/01.sql
      - ./migrations/scripts/create_schema.sql:/docker-entrypoint-initdb.d/02.sql

  alembic:
    build:
      target: alembic-image
      context: .
    environment:
      RDS_HOST: postgres-db
      RDS_PORT: 5432
      RDS_USERNAME: postgres
      RDS_PASSWORD: postgres
      RDS_NAME: dataops
      RDS_SCHEMA: dataops
    env_file:
      - .env
    depends_on:
      - postgres-db
